### ISSUE TITLE
The animation is not smooth

### ISSUE THREAD

**Issue by r0b78** [koffiisen/js-splash#1]
This is more a request feature than and issue, good work keep going

**Comment by koffiisen** [comment]
Hello, 
thank you for your message. 
Yes, it is the first version. Another version is being developed and I will take your remark into account. 
Any other ideas for improvement? 
Do not hesitate to share and make known this library. 
Thank you

**Comment by koffiisen** [comment]
Hi,

just inform you that version 2.0 is available.
I tried to heed your remark.
Now it is possible to make animation and make it smooth.

Documentation here https://koffiisen.github.io/js-splash/




________________________________
De : r0b78 <notifications@github.com>
Envoyé : mardi 25 février 2020 à 05:26
À : koffiisen/js-splash
Cc : Subscribed
Objet : [koffiisen/js-splash] The animation is not smooth (#1)


This is more a request feature than and issue, good work keep going

**Comment by koffiisen** [comment]
Hi,

Just inform you that version 2.0 is available.
I tried to heed your remark.

Now it is possible to make aanimation and make it smooth

Documentation here https://koffiisen.github.io/js-splash/

**Comment by koffiisen** [comment]
Hello,
Here is my last library [Animate.js]( https://github.com/koffiisen/Animate.js )
 [Demo here](https://koffiisen.github.io/Animate.js/)

**Comment by r0b78** [comment]
Nice see alot of impovment !

**Comment by koffiisen** [comment]
> Nice see alot of impovment !

Thank you. 

The inspiration come from this [Animate.css](https://github.com/daneden/animate.css) and i update my repository to [Animate.js](https://github.com/koffiisen/Animate.js)

Best regards
